python train.py \
--train_size=-1 \
--val_size=-1 \
--test=-1 \
--epoch=50 \
--verbose=500 \
--learning_rate=5e-4 \
--weight_decay=1e-5 \
--batch_size=256 \
--gpu=0 \
--pretrained=resnet \
--attention=spatial \
--evaluation=true