python train.py \
--train_size=100 \
--val_size=10 \
--test=10 \
--epoch=10 \
--verbose=1000 \
--learning_rate=2e-4 \
--weight_decay=1e-5 \
--batch_size=100 \
--gpu=2 \
--pretrained=resnet \
--attention=att2in \
--evaluation=true